config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #get 'admincontact/new'
  #get 'user/new' => 'user#new'
  #
  resources :user, only: [:new, :create]
  resources :contact, only: [:new, :create]
  resources :admincontact, only: [:new, :create]

  get '/services' => 'static_pages#services'
  get '/staff' => 'static_pages#staff'
  get '/news' => 'static_pages#news'
  get '/training' => 'static_pages#training'
  get '/contact' => 'contact#new'
  get '/work_with_us' => 'user#new'
  get '/alert_message' => 'static_pages#alert_message'
  get '/admincontact' => 'admincontact#new'
  get '/faq' => 'static_pages#faq'
  get '/working' => 'static_pages#working'
  get '/history' => 'static_pages#history'
  get '/how' => 'static_pages#how'
  get '/info' => 'static_pages#info'

  post 'user/new' => 'user#create'
  post 'contact/new' => 'contact#create'
  post 'admincontact/new' => 'admincontact#create'

  root 'static_pages#home'
end

app/models/admincontact.rb
class Admincontact < MailForm::Base

  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :mensaje,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
        :subject => 'Admin Contact desde Web Andares',
        :to => 'diegodev9@gmail.com',


    }
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base

  attribute :nombre,    :validate => true
  attribute :apellido,  :validate => true
  attribute :asunto,    :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :mensaje,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
        :subject => "Contacto desde Web Andares",
        :to => "andaresequipo@gmail.com",


    }
  end

end

app/models/user.rb
class User < MailForm::Base

  attribute :profesion, :validate => true
  attribute :nombre, :validate => true
  attribute :apellido, :validate => true
  attribute :direccion, :validate => true
  attribute :ciudad, :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :mensaje
  attribute :file, :attachment => true
  attribute :nickname,  :captcha  => true

  def headers
    {
        :subject => "Curriculum desde Web Andares",
        :to => "andaresequipo@gmail.com",


    }
  end

end

app/controllers/admincontact_controller.rb
class AdmincontactController < ApplicationController

  def new
    @header_image = 'images/developer_working.jpg'
    @admincontact = Admincontact.new(params[:admincontact])
  end

  def create
    @admincontact = Admincontact.new(params[:admincontact])
    @admincontact.request = request
    if !@admincontact.deliver
      puts('error al enviar')
      redirect_to root_path
    else
      @admincontact = Admincontact.new
      puts('Envio con exito')

      redirect_to root_path
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @class_contact = 'active'
    @header_image = 'images/img_bg_1.jpg'
    @contact = Contact.new(params[:contact])
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if !@contact.deliver
      puts('error al enviar')
      $alert_error = true
      $alert_message = 'Hubo un error al enviar su mensaje, intente nuevamente'
      redirect_to '/alert_message'
    else
      @contact = Contact.new
      puts('Envio con exito')
      $alert_message = 'Su mensaje fue enviado'
      redirect_to '/alert_message'
    end

  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @class_home = 'active'
    @header_image = 'images/img_bg_1.jpg'
  end

  def services
    @class_services = 'active'
    @header_image = 'images/services12.jpg'
  end

  def staff
    @class_who = 'active'
    @header_image = 'images/IMG_20190416_114246.jpg'
  end

  def news
    @class_info = 'active'
    @header_image = 'images/news.jpg'
  end

  def training
    @class_training = 'active'
    @header_image = 'images/training.jpg'
  end

  def faq
    @class_info = 'active'
    @header_image = 'images/dudas.jpg'
  end

  def working
    @header_image = 'images/working.jpg'
  end

  def history
    @class_who = 'active'
    @header_image = 'images/andares_old9.jpg'
  end

  def how
    @class_who = ' active'
    @header_image = 'images/how_portada.jpg'
  end

  def info
    @class_info = 'active'
    @header_image = 'images/info.jpg'
  end

  def alert_message
    @header_image = 'images/gracias.jpg'
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def new
    @header_image = 'images/grupalandares.jpg'
    @user = User.new(params[:user])
  end

  def create
    @user = User.new(params[:user])
    @user.request = request
    if !@user.deliver
      puts('error al enviar')
      $alert_error = true
      $alert_message = 'Hubo un error al enviar su mensaje, intente de nuevo'
      redirect_to '/alert_message'
    else
      @user = User.new
      puts('Envio con exito')

      $alert_message = 'Su mensaje fue enviado'
      redirect_to '/alert_message'
    end
  end

end

app/helpers/admincontact_helper.rb
module AdmincontactHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper


end

app/views/admincontact/new.html.erb
<div class="fh5co-loader"></div>
<div id="page">
  <%= render 'partials/header' %>
  <div id="fh5co-contact">
    <div class="container">
      <div class="row">

      </div>
      <div class="row">
        <div class="col-md-12 animate-box">
          <h3>Contactar con el Web Admin</h3>
          <%= form_for @admincontact, url: admincontact_new_path, remote: true do |f| %>

            <div class="row form-group">
              <div class="col-md-12">
                <%= f.text_field :email, required: true, class:'form-control', placeholder:'E-mail' %>
              </div>
            </div>

            <div class="row form-group">
              <div class="col-md-12">
                <%= f.text_field :mensaje, class:'form-control', cols:'30', rows:'10', required: true, placeholder:'Mensaje' %>
              </div>
            </div>

            <div class="row form-group">
              <div class="col-md-12">
                <%= f.text_field :nickname, hint: 'leave this field blank', class:'hide' %>
              </div>
            </div>

            <div class="form-group text-center">
              <%= f.submit 'Enviar', class:'btn btn-lg btn-primary', data: {disable_with: 'Enviando...'} %>
            </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/contact/new.html.erb
<div class="fh5co-loader"></div>
<div id="page">
  <%= render 'partials/header' %>
  <div id="fh5co-contact">
    <div class="container">
      <div class="row">

        <div class="col-md-6 col-md-push-1 col-sm-5 col-sm-push-0 text-center">
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2749.603070651212!2d-67.51917528462343!3d-46.43674648220577!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xbde5dfa527ffa8a9%3A0x35c39ba3c2adee6d!2sHip%C3%B3lito+Yrigoyen+424%2C+Caleta+Olivia%2C+Santa+Cruz!5e0!3m2!1ses-419!2sar!4v1559771389865!5m2!1ses-419!2sar" width="300" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>

        <div class="col-md-6 col-md-push-1 col-sm-6 col-sm-push-2 col-xs-10 col-xs-push-1 animate-box">
          <div class="fh5co-contact-info">
            <h3>Información de contacto</h3>
            <ul>
              <li class="address"><a href="https://www.google.com/maps/embed?pb=!1m17!1m11!1m3!1d1531.8266792778657!2d-67.51696483842618!3d-46.43679454773219!2m2!1f0!2f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xbde5dfa527ffa8a9%3A0x35c39ba3c2adee6d!2sHip%C3%B3lito+Yrigoyen+424%2C+Caleta+Olivia%2C+Santa+Cruz!5e1!3m2!1ses-419!2sar!4v1555006399529!5m2!1ses-419!2sar">Pte. Hipólito Yrigoyen 2412 <br>Caleta Olivia Z9011AYJ <br>Santa Cruz </a></li>
              <li class="phone"><a href="tel://1234567920">+54 9 297 424-5331</a></li>
              <li class="email"><a href="mailto:andaresequipo@gmail.com">andaresequipo@gmail.com</a></li>
              <li class="url"><a href="https://www.facebook.com/andares.caletaolivia" target="_blank">Andares Caleta Olivia</a></li>
            </ul>
          </div>
        </div>

      </div>
      <div class="row">
        <div class="col-md-12 animate-box">
          <h3>Escríbenos</h3>
          <%= form_for @contact, url: contact_new_path, remote: true do |f| %>
            <div class="row form-group">
              <div class="col-md-6">
                <%= f.text_field :nombre , required: true, class:'form-control', placeholder:'Nombre' %>
              </div>
              <div class="col-md-6">
                <%= f.text_field :apellido, required: true, class:'form-control', placeholder:'Apellido' %>
              </div>
            </div>

            <div class="row form-group">
              <div class="col-md-12">
                <%= f.text_field :email, required: true, class:'form-control', placeholder:'E-mail' %>
              </div>
            </div>

            <div class="row form-group">
              <div class="col-md-12">
                <%= f.text_field :asunto, required: true, class:'form-control', placeholder:'Asunto del mensaje' %>
              </div>
            </div>

            <div class="row form-group">
              <div class="col-md-12">
                <%= f.text_field :mensaje, class:'form-control', cols:'30', rows:'10', required: true, placeholder:'Mensaje' %>
              </div>
            </div>

            <div class="row form-group">
              <div class="col-md-12">
                <%= f.text_field :nickname, hint: 'leave this field blank', class:'hide' %>
              </div>
            </div>

            <div class="form-group text-center">
              <%= f.submit 'Enviar', class:'btn btn-lg btn-primary', data: {disable_with: 'Enviando...'} %>
            </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Andares</title>
    <meta name="title" content="Andares Caleta Olivia">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Andares es un equipo de profesionales especializados en el desarrollo infantil. Esta situado en la ciudad de Caleta Olivia - Santa Cruz. Se atiende niños y niñas de diferentes edades con distintos tipos de diagnósticos" />
    <meta name="keywords"
          content="andares, equipo, tel, autismo, tea, clinica, fonoaudiologia, estimulacion, neurodesarrollo, caleta, olivia, argentina, kinesiologia, tgd, trastorno de lenguaje, deficit de desarrollo" />
    <meta name="author" content="diegodev9">
    <meta name="robots" content="noindex,nofollow">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">

    <!-- Animate.css -->
    <link rel="stylesheet" href="css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="css/icomoon.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

    <!-- Magnific Popup -->
    <link rel="stylesheet" href="css/magnific-popup.css">

    <!-- Theme style  -->
    <link rel="stylesheet" href="css/style.css">

    <!-- Modernizr JS -->
    <script src="js/modernizr-2.6.2.min.js"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
    <script src="js/respond.min.js"></script>
    <![endif]-->

    <!-- Favicon -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
    <link rel="icon" href="images/favicon.ico" type="image/x-icon">

    <!--Rails tags-->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header>
      <nav>
        <%= render 'partials/navbar' %>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <%= render 'partials/footer' %>
    </footer>
    <%= render 'partials/uparrow' %>

    <!-- jQuery -->
    <script src="js/jquery.min.js"></script>
    <!-- jQuery Easing -->
    <script src="js/jquery.easing.1.3.js"></script>
    <!-- Bootstrap -->
    <script src="js/bootstrap.min.js"></script>
    <!-- Waypoints -->
    <script src="js/jquery.waypoints.min.js"></script>
    <!-- countTo -->
    <script src="js/jquery.countTo.js"></script>
    <!-- Magnific Popup -->
    <script src="js/jquery.magnific-popup.min.js"></script>
    <script src="js/magnific-popup-options.js"></script>
    <!-- Stellar -->
    <script src="js/jquery.stellar.min.js"></script>
    <!-- Main -->
    <script src="js/main.js"></script>

  </body>
</html>

app/views/partials/_andares_old.html.erb
<div class="row">
  <div class="container-fluid">
      <div id="myCarousel" class=" center-block carousel slide" data-ride="carousel" style="max-width: 425px;">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
          <li data-target="#myCarousel" data-slide-to="3"></li>
          <li data-target="#myCarousel" data-slide-to="4"></li>
          <li data-target="#myCarousel" data-slide-to="5"></li>
          <li data-target="#myCarousel" data-slide-to="6"></li>
          <li data-target="#myCarousel" data-slide-to="7"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <div class="item active">
            <img src="images/andares_old1.png" alt="" style="width: 100%;">
          </div>

          <div class="item">
            <img src="images/andares_old2.png" alt="" style="width:100%;">
          </div>

          <div class="item">
            <img src="images/andares_old3.png" alt="" style="width:100%;">
          </div>

          <div class="item">
            <img src="images/andares_old4.png" alt="" style="width:100%;">
          </div>

          <div class="item">
            <img src="images/andares_old5.png" alt="" style="width:100%;">
          </div>

          <div class="item">
            <img src="images/andares_old6.png" alt="" style="width:100%;">
          </div>

          <div class="item">
            <img src="images/andares_old7.png" alt="" style="width:100%;">
          </div>

          <div class="item">
            <img src="images/andares_old8.png" alt="" style="width:100%;">
          </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
  </div>

</div>

app/views/partials/_footer.html.erb
<footer id="fh5co-footer" role="contentinfo">
  <div class="container text-center">
    <div class="row row-pb-md">

      <div class="col-md-6 col-sm-6 col-xs-6 fh5co-widget text-left">
        <img src="images/g12.png" style="width: 150px; height: auto;" alt=""><br><br>
        <p>Pte. Hipólito Yrigoyen 2412 <br>Caleta Olivia Z9011AYJ <br>Santa Cruz <br>Tel. +54 9 297 424-5331</p>
      </div>
      <br><br>
      <div class="col-md-6 col-sm-6 col-xs-6 text-right">
        <ul class="fh5co-footer-links">
          <li><%= link_to 'Preguntas Frecuentes', faq_path %></li>
          <li><%= link_to 'Información para Pacientes', info_path %></li>
          <li><%= link_to 'Profesionales', staff_path %></li>
          <li><%= link_to 'Trabajar en ANDARES', work_with_us_path %></li>
          <li><%= link_to 'Contacto', contact_path %></li>
        </ul>
      </div>
    </div>

    <div class="row copyright">
      <div class="col-md-12 text-center">
        <p>
          <small class="block">&copy; 2019 All Rights Reserved.</small>
          <!--<small class="block">Diseñada por GetTemplates.co</small>-->
          <small><%= link_to 'diegodev9', admincontact_path, class:'block' %></small>
        </p>
        <p>
        <ul class="fh5co-social-icons">
          <li><a href="https://twitter.com/andares_caleta?lang=es" target="_blank"><i class="icon-twitter"></i></a></li>
          <li><a href="https://www.facebook.com/andares.caletaolivia" target="_blank"><i class="icon-facebook"></i></a></li>
          <li><a href="#"><i class="icon-linkedin"></i></a></li>
          <li><a href="https://api.whatsapp.com/send?phone=5492974245331" target="_blank"><i class="icon-dribbble"></i></a></li>
        </ul>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/partials/_header.html.erb
<header id="fh5co-header" class="fh5co-cover fh5co-cover-sm" role="banner" style="background-image:url(<%= @header_image %>);"
        data-stellar-background-ratio="1.0">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-7 text-left">
        <div class="display-t">
          <div class="display-tc animate-box" data-animate-effect="fadeInUp">
            <h1 class="mb30">
              <%= @header_text %>
            </h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/partials/_how.html.erb
<div class="fh5co-loader"></div>
<div class="row">
  <div class="container-fluid">
    <div id="myCarousel" class=" center-block carousel slide" data-ride="carousel" style="max-width: 768px;">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
        <li data-target="#myCarousel" data-slide-to="5"></li>
        <li data-target="#myCarousel" data-slide-to="6"></li>
        <li data-target="#myCarousel" data-slide-to="7"></li>
        <li data-target="#myCarousel" data-slide-to="8"></li>
        <li data-target="#myCarousel" data-slide-to="9"></li>
        <li data-target="#myCarousel" data-slide-to="10"></li>
        <li data-target="#myCarousel" data-slide-to="11"></li>
        <li data-target="#myCarousel" data-slide-to="12"></li>
        <li data-target="#myCarousel" data-slide-to="13"></li>
        <li data-target="#myCarousel" data-slide-to="14"></li>
        <li data-target="#myCarousel" data-slide-to="15"></li>
        <li data-target="#myCarousel" data-slide-to="16"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <img src="images/how_2.jpg" alt="" style="width:100%;">
        </div>

        <div class="item">
          <img src="images/how_3.jpg" alt="" style="width:100%;">
        </div>

        <div class="item">
          <img src="images/how_4.jpg" alt="" style="width:100%;">
        </div>

        <div class="item">
          <img src="images/how_5.jpg" alt="" style="width:100%;">
        </div>

        <div class="item">
          <img src="images/how_6.jpg" alt="" style="width:100%;">
        </div>

        <div class="item">
          <img src="images/how_7.jpg" alt="" style="width:100%;">
        </div>

        <div class="item">
          <img src="images/how_9.jpg" alt="" style="width:100%;">
        </div>

        <div class="item">
          <img src="images/how_10.jpg" alt="" style="width:100%;">
        </div>

        <div class="item">
          <img src="images/how_11.jpg" alt="" style="width:100%;">
        </div>

        <div class="item">
          <img src="images/how_12.jpg" alt="" style="width:100%;">
        </div>

        <div class="item">
          <img src="images/how_13.jpg" alt="" style="width:100%;">
        </div>

        <div class="item">
          <img src="images/how_14.jpg" alt="" style="width:100%;">
        </div>

        <div class="item">
          <img src="images/how_15.jpg" alt="" style="width:100%;">
        </div>

        <div class="item">
          <img src="images/how_16.jpg" alt="" style="width:100%;">
        </div>

        <div class="item">
          <img src="images/how_17.jpg" alt="" style="width:100%;">
        </div>

        <div class="item">
          <img src="images/how_18.jpg" alt="" style="width:100%;">
        </div>
      </div>

      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>

</div>

app/views/partials/_navbar.html.erb
<nav class="fh5co-nav" role="navigation">
  <div class="container">
    <div class="row">
      <div class="col-md-2 col-xs-12 text-left">
        <!-- <div id="fh5co-logo">
          <a href="work_with_us.html">andares<span>.</span><small id="fh5co-logo2">Equipo para la Atención del Desarrollo Infantil</small></a>
        </div> -->
        <div id="fh5co-logo2">
          <%= link_to '<img src="images/g12.png" style="width: 200px; height: auto;" alt="">'.html_safe, root_path %>
        </div>
      </div>
      <div class="col-md-10 col-xs-12 text-right menu-1">
        <ul>
          <li class=<%= @class_home %>>
            <%= link_to 'Inicio', root_path %>
          </li>
          <li class=<%= @class_services %>>
            <%= link_to 'Servicios', services_path %>
          </li>
          <li class="has-dropdown <%= @class_who %>">
            <a>¿Quienes somos?</a>
            <ul class="dropdown">
              <li><%= link_to 'Historia', history_path %></li>
              <li><%= link_to 'Profesionales', staff_path %></li>
              <li><%= link_to 'Como trabajamos', how_path %></li>
            </ul>
          </li>
          <li class="has-dropdown <%= @class_info %>">
            <a>Información útil</a>
            <ul class="dropdown">
              <li><%= link_to 'Preguntas Frecuentes', faq_path %></li>
              <li><%= link_to 'Información para Pacientes', info_path %></li>
              <li><%= link_to 'Noticias', news_path %></li>
            </ul>
          </li>
          <li class=<%= @class_training %>><%= link_to 'Capacitación', training_path %></li>
          <li class=<%= @class_contact %>><%= link_to 'Contacto', contact_path %></li>
        </ul>
      </div>
    </div>

  </div>
</nav>

app/views/partials/_notifications.html.erb
<% if !notice.nil? %>
  <div class="alert alert-dismissible alert-info">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= notice %>
  </div>
<% end %>

app/views/partials/_uparrow.html.erb
<div class="gototop js-top">
  <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
</div>

app/views/partials/_workwithus.html.erb
<div id="fh5co-started">
  <div class="container">
    <div class="row animate-box" data-animate-effect="fadeInUp">
      <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
        <span>Quéres trabajar con nosotros?</span>
        <h2>Envianos Tu Curriculum</h2>
        <p>El equipo ANDARES se encuentra en constante crecimiento y por eso necesitamos de profesionales como vos
          para seguir avanzando.</p>
        <%= link_to '<button type=submit class="block-center btn btn-primary">Enviar</button>'.html_safe, work_with_us_path %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="fh5co-loader"></div>
<div id="page">
  <%= render 'partials/header' %>
  <%= render 'partials/initial_comment' %>
  <%= render 'partials/statistics' %>
  <%#= render 'partials/intro' %>
  <%= render 'partials/services' %>
  <%= render 'partials/obras_sociales' %>
  <%= render 'partials/workwithus' %>
</div>

app/views/static_pages/working.html.erb
<div class="fh5co-loader"></div>
<% @header_text='Oops! Sección en Desarrollo' %>
<div id="page">
  <%= render 'partials/header' %>
</div>

app/views/user/new.html.erb
<div class="fh5co-loader"></div>
<div id="page">
  <%= render 'partials/header' %>
  <div id="fh5co-contact" style="margin-left: 40px; margin-right:40px;">
    <div class="container">
      <div class="row">

        <div class="row">
          <div class="col-md-12 animate-box" >
            <h3>Tus Datos</h3>
            <%= form_for @user, url: user_new_path, html: { multipart: true }, remote: true do |f| %>
              <div class="row form-group">
                <div class="col-md-4">
                  <%= f.text_field :profesion, required: true, class:'form-control', placeholder:'Profesión' %>
                </div>
                <div class="col-md-4">
                  <%= f.text_field :nombre, class:'form-control', placeholder:'Nombre', required: true %>
                </div>
                <div class="col-md-4">
                  <%= f.text_field :apellido, class:'form-control', placeholder:'Apellido', required: true %>
                </div>

              </div>

              <div class="row form-group">
                <div class="col-md-4">
                  <%= f.text_field :direccion, class:'form-control', placeholder:'Dirección', required: true %>
                </div>
                <div class="col-md-4">
                  <%= f.text_field :ciudad, class:'form-control', placeholder:'Localidad/Provincia', required: true %>
                </div>
                <div class="col-md-4">
                  <%= f.text_field :email, class:'form-control', placeholder:'E-mail', required:true %>
                </div>

              </div>

              <div class="row form-group">
                <div class="col-md-12">
                  <%= f.text_field :mensaje, class:'form-control', placeholder:'Mensaje (opcional)' %>
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-6 col-md-offset-3">
                  <%= f.file_field :file, class:"form-control", required: true %>
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-6 col-md-offset-3">
                  <%= f.text_field :nickname, hint: 'leave this field blank', class:'hide' %>
                </div>
              </div>

              <div class="form-group text-center">
                <%= f.submit 'Enviar', class:"btn btn-lg btn-primary", data: { disable_with: 'Enviando...' } %>
              </div>

            <% end %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>